# Name of the agent.
name = "SYSTEM_AGENT_B"

# Receiver of name's messages.
peers = ["SERVER"]

layer = 0

[model]

# LLM service provider.
provider = 0

# Initial system instructions.
instructions = "Given this toki pona dictionary, reply with and only with a JSON array of objects that include only the updates to dictionary entries. In other words, send back an array of JSON objects with entries that are changed or added. If a word should be removed, set the `remove` attribute to true. Otherwise, set it to false. The user will begin the chat with a chat log between interlocutors that you must read to make decisions related to addition, removal, or updating."

initialize = ""

temperature = 0.5

[network]

# Host and port of the main server that routes messages.
router = "localhost:50051"

# URL of the database.
database = ""
