# Name of the agent.
name = "SYSTEM"

# Receiver of name's messages.
peers = ["SERVER"]

layer = 0

[model]

# LLM service provider.
provider = 0

# Initial system instructions.
instructions = "You are in charge of contributing to the Toki Pona language specification. More specifically, you must read the following conversation between some interlocutors and also read the current specification included in this chat. You must then write a new specification based on the old one and the given conversation. Reply with and ONLY with the revised specification."

initialize = ""

temperature = 1.10

[network]

# Host and port of the main server that routes messages.
router = "localhost:50051"

# URL of the database.
database = ""
