version: "3"
tasks:
  fmt:
    cmds:
      - nix fmt .
  lint:
    cmds:
      - golangci-lint run
  count:
    cmds:
      - tokei --exclude "*.{svg,json,yml,yaml}" .
  up-deps:
    cmds:
      - go get -u ./...
      - go mod vendor
  gen-proto-chat:
    cmds:
      - protoc --go_out=./chat/ --go-grpc_out=./chat/ ./chat/chat.proto
  run-agent-toki:
    cmds:
      - go run ./cmd/agent -debug=true -temperature=0.87 -layer=1 -name="toki" -peers="pona" -model=5
  run-agent-pona:
    cmds:
      - go run ./cmd/agent -debug=true -temperature=0.75 -layer=1 -name="pona" -peers="toki" -model=1
  run-agent-penny:
    cmds:
      - go run ./cmd/agent -debug=true -temperature=0.75 -layer=2 -name="penny" -peers="tails" -model=5
  run-agent-tails:
    cmds:
      - go run ./cmd/agent -debug=true -temperature=0.74 -layer=2 -name="tails" -peers="penny" -model=0
  run-agent-nickel:
    cmds:
      - go run ./cmd/agent -debug=true -temperature=0.78 -layer=3 -name="nickel" -peers="dime" -model=1
  run-agent-dime:
    cmds:
      - go run ./cmd/agent -debug=true -temperature=0.81 -layer=3 -name="dime" -peers="nickel" -model=5
  run-agent-tako:
    cmds:
      - go run ./cmd/agent -debug=true -temperature=0.78 -layer=4 -name="tako" -peers="ono" -model=1
  run-agent-ono:
    cmds:
      - go run ./cmd/agent -debug=true -temperature=0.76 -layer=4 -name="ono" -peers="tako" -model=0
  run-agent-system-a:
    cmds:
      - go run ./cmd/agent -configFile="./cmd/configs/sys_agent.toml" -debug=true -model=5
  run-agent-system-b:
    cmds:
      - go run ./cmd/agent -configFile="./cmd/configs/sys_agent_b.toml" -debug=true -model=1
  run-agent-system-c:
    cmds:
      - go run ./cmd/agent -configFile="./cmd/configs/sys_agent_c.toml" -debug=true -model=1
  run-agent-system-logogram-gen:
    cmds:
      - go run ./cmd/agent -configFile="./cmd/configs/sys_agent_logogram.toml" -debug=true -model=5 -name="SYSTEM_AGENT_D" -temperature=0.75
  run-agent-system-logogram-adv:
    cmds:
      - go run ./cmd/agent -configFile="./cmd/configs/sys_agent_logogram.toml" -debug=true -model=1 -name="SYSTEM_AGENT_E" -temperature=0.75
  run-server:
    cmds:
      - go run ./cmd/server -debug=true -logToFile=false -exchanges=7 -generations=2 -broadcastTestData=false
  run-web:
    cmds:
      - cd frontend && pnpm dev
