version: '3'
tasks:
  # Run commands
  run-agent-toki:
    cmds:
      - go run ./agent -configFile="./configs/b1.toml"
  run-agent-pona:
    cmds:
      - go run ./agent -configFile="./configs/b2.toml"
  run-agent-toki-a1:
    cmds:
      - go run ./agent -configFile="./configs/a1.toml"
  run-agent-pona-a2:
    cmds:
      - go run ./agent -configFile="./configs/a2.toml"
  run-server:
    cmds:
      - go run ./server
  # utils
  gen-proto-chat:
    cmds:
      - protoc --go_out=./chat/ --go-grpc_out=./chat/ chat.proto
