version: "3"
tasks:
  # Run commands
  run-agent-toki:
    cmds:
      - go run ./agent -debug=true -initialize="./configs/default_message.txt" -temperature=1.62 -layer=1 -name="toki" -peers="pona" -model=0
  run-agent-pona:
    cmds:
      - go run ./agent -debug=true -temperature=1.62 -layer=1 -name="pona" -peers="toki"
  run-agent-toki-a1:
    cmds:
      - go run ./agent -configFile="./configs/a1.toml" -debug=true
  run-agent-pona-a2:
    cmds:
      - go run ./agent -configFile="./configs/a2.toml" -debug=true
  run-server:
    cmds:
      - go run ./server/cmd -debug=true -logToFile=false
  # utils
  gen-proto-chat:
    cmds:
      - protoc --go_out=./chat/ --go-grpc_out=./chat/ ./chat/chat.proto
