version: '3'

tasks:
  # Run commands
  run-agent-toki-gemini:
    cmds:
      - go run ./agent -name=toki -recipient=pona -model=0
  run-agent-pona-gemini:
    cmds:
      - go run ./agent -name=pona -recipient=toki -model=0
  run-agent-toki-ollama:
    cmds:
      - go run ./agent -name=toki -recipient=pona -model=3
  run-agent-pona-ollama:
    cmds:
      - go run ./agent -name=pona -recipient=toki -model=3

  run-server:
    cmds:
      - go run ./server

  gen-proto-chat:
    cmds:
      - protoc --go_out=./chat/ --go-grpc_out=./chat/ chat.proto
