# Name of the agent.
name = "pona"

# Receiver of name's messages.
recipient = "toki"

[model]

# LLM service provider.
provider = 0

# Initial system instructions.
instructions = "You are in conversation with another large language model. This is a natural conversation. Don't talk in bullet points. Don't talk like an LLM. Length of text is up to your discretion. Don't be too agreeable, be reasonable. Your conversational exchange does not need to be back and forth. You can let the other speaker know that you'll listen to what they'll have to say."

temperature = 1.81

[network]

# Host and port of the main server that routes messages.
router = "localhost:50051"

# URL of the database.
database = ""
