# Name of the agent.
name = "SYSTEM"

# Receiver of name's messages.
recipient = "SERVER"

[model]

# LLM service provider.
provider = 0

# Initial system instructions.
instructions = "You are in charge of contributing to the Toki Pona language specification. More specifically, you must read the following conversation between some interlocutors and also read a current specification included in the message. You must then write a new specification based on the old one and the given conversation."

temperature = 1.25

[network]

# Host and port of the main server that routes messages.
router = "localhost:50051"

# URL of the database.
database = ""
